import { ExtensionManager, MODULE_TYPES } from './extensions';
import { ServiceProvidersManager, ServicesManager } from './services';
import classes, { CommandsManager, HotkeysManager } from './classes';
import { SystemContextProvider, useSystem } from './contextProviders/SystemProvider';
import { ViewportRefsProvider } from './hooks/useViewportRef';
import DICOMWeb from './DICOMWeb';
import errorHandler from './errorHandler.js';
import log from './log.js';
import object from './object.js';
import string from './string.js';
import user from './user';
import utils from './utils';
import defaults from './defaults';
import * as Types from './types';
import * as Enums from './enums';
import { CineService, UIDialogService, UIModalService, UINotificationService, UIViewportDialogService, DicomMetadataStore, DisplaySetService, ToolbarService, MeasurementService, ViewportGridService, HangingProtocolService, pubSubServiceInterface, PubSubService, UserAuthenticationService, CustomizationService, PanelService, WorkflowStepsService, StudyPrefetcherService, MultiMonitorService } from './services';
import { DisplaySetMessage, DisplaySetMessageList } from './services/DisplaySetService';
import IWebApiDataSource from './DataSources/IWebApiDataSource';
import useActiveViewportDisplaySets from './hooks/useActiveViewportDisplaySets';
export * from './hooks';
declare const hotkeys: any;
declare const OHIF: {
    MODULE_TYPES: typeof MODULE_TYPES;
    CommandsManager: typeof classes.CommandsManager;
    ExtensionManager: typeof ExtensionManager;
    HotkeysManager: typeof classes.HotkeysManager;
    ServicesManager: typeof ServicesManager;
    ServiceProvidersManager: typeof ServiceProvidersManager;
    defaults: typeof defaults;
    utils: {
        guid: typeof import("./utils").guid;
        uuidv4: typeof import("./utils/uuidv4").default;
        ObjectPath: typeof import("./utils").ObjectPath;
        absoluteUrl: typeof import("./utils").absoluteUrl;
        sortBy: typeof import("./utils").sortBy;
        sortBySeriesDate: (series: any, seriesSortingCriteria?: typeof import("./utils/sortStudy").seriesInfoSortingCriteria, sortFunction?: any) => any;
        sortStudy: typeof import("./utils/sortStudy").sortStudy;
        sortStudySeries: (series: any, seriesSortingCriteria?: typeof import("./utils/sortStudy").seriesInfoSortingCriteria, sortFunction?: any) => any;
        sortStudyInstances: (instancesList: any, instancesSortingCriteria?: (a: any, b: any) => number) => any;
        sortDisplaySetsCopy: typeof import("./utils/sortStudy").sortDisplaySetsCopy;
        sortingCriteria: {
            seriesSortCriteria: {
                default: typeof import("./utils/sortStudy").seriesInfoSortingCriteria;
                seriesInfoSortingCriteria: typeof import("./utils/sortStudy").seriesInfoSortingCriteria;
                compareSameSeries: (a: any, b: any) => number;
                compareSeriesDateTime: (a: any, b: any) => number;
                compareSeriesUID: (a: any, b: any) => number;
            };
            instancesSortCriteria: {
                default: (a: any, b: any) => number;
                sortByInstanceNumber: (a: any, b: any) => number;
            };
        };
        seriesSortCriteria: {
            default: typeof import("./utils/sortStudy").seriesInfoSortingCriteria;
            seriesInfoSortingCriteria: typeof import("./utils/sortStudy").seriesInfoSortingCriteria;
            compareSameSeries: (a: any, b: any) => number;
            compareSeriesDateTime: (a: any, b: any) => number;
            compareSeriesUID: (a: any, b: any) => number;
        };
        instancesSortCriteria: {
            default: (a: any, b: any) => number;
            sortByInstanceNumber: (a: any, b: any) => number;
        };
        writeScript: typeof import("./utils").writeScript;
        formatDate: typeof import("./utils").formatDate;
        formatTime: typeof import("./utils/formatTime").default;
        formatPN: typeof import("./utils/formatPN").default;
        b64toBlob: typeof import("./utils").b64toBlob;
        urlUtil: typeof import("./utils").urlUtil;
        imageIdToURI: typeof import("./utils").imageIdToURI;
        makeDeferred: typeof import("./utils").makeDeferred;
        makeCancelable: typeof import("./utils").makeCancelable;
        structuredCloneWithFunctions: typeof import("./utils").structuredCloneWithFunctions;
        hotkeys: any;
        Queue: typeof import("./utils").Queue;
        isDicomUid: typeof import("./utils").isDicomUid;
        isEqualWithin: typeof import("./utils").isEqualWithin;
        sopClassDictionary: typeof import("./utils/sopClassDictionary").sopClassDictionary;
        addAccessors: typeof import("./utils/addAccessors").default;
        resolveObjectPath: typeof import("./utils").resolveObjectPath;
        hierarchicalListUtils: typeof import("./utils").hierarchicalListUtils;
        progressTrackingUtils: typeof import("./utils").progressTrackingUtils;
        isLowPriorityModality: typeof import("./utils").isLowPriorityModality;
        isImage: typeof import("./utils").isImage;
        isDisplaySetReconstructable: typeof import("./utils").isDisplaySetReconstructable;
        debounce: typeof import("./utils").debounce;
        roundNumber: typeof import("./utils").roundNumber;
        toNumber: typeof import("./utils").toNumber;
        downloadCSVReport: typeof import("./utils").downloadCSVReport;
        splitComma: (strings: string[]) => string[];
        getSplitParam: (lowerCaseKey: string, params?: URLSearchParams) => string[];
        generateAcceptHeader: (configAcceptHeader?: string[], requestTransferSyntaxUID?: string, omitQuotationForMultipartRequest?: boolean) => string[];
        createStudyBrowserTabs: typeof import("./utils").createStudyBrowserTabs;
        MeasurementFilters: typeof import("./utils/measurementFilters");
        getClosestOrientationFromIOP: typeof import("./utils").getClosestOrientationFromIOP;
        calculateScanAxisNormal: typeof import("./utils/calculateScanAxisNormal").default;
        areAllImageOrientationsEqual: typeof import("./utils/areAllImageOrientationsEqual").default;
        downloadBlob: typeof import("./utils").downloadBlob;
        downloadUrl: typeof import("./utils").downloadUrl;
        downloadCsv: typeof import("./utils").downloadCsv;
        downloadDicom: typeof import("./utils").downloadDicom;
    };
    hotkeys: any;
    classes: typeof classes;
    string: typeof string;
    user: {
        userLoggedIn: () => boolean;
        getUserId: () => any;
        getName: () => any;
        getAccessToken: () => any;
        login: () => Promise<unknown>;
        logout: () => Promise<unknown>;
        getData: (key: any) => any;
        setData: (key: any, value: any) => any;
    };
    errorHandler: typeof errorHandler;
    object: typeof object;
    log: typeof log;
    DICOMWeb: typeof DICOMWeb;
    viewer: {};
    CineService: typeof CineService;
    CustomizationService: typeof CustomizationService;
    UIDialogService: typeof UIDialogService;
    UIModalService: typeof UIModalService;
    UINotificationService: typeof UINotificationService;
    UIViewportDialogService: typeof UIViewportDialogService;
    DisplaySetService: typeof DisplaySetService;
    MeasurementService: typeof MeasurementService;
    ToolbarService: typeof ToolbarService;
    ViewportGridService: typeof ViewportGridService;
    HangingProtocolService: typeof HangingProtocolService;
    UserAuthenticationService: typeof UserAuthenticationService;
    MultiMonitorService: typeof MultiMonitorService;
    IWebApiDataSource: typeof IWebApiDataSource;
    DicomMetadataStore: {
        EVENTS: {
            STUDY_ADDED: string;
            INSTANCES_ADDED: string;
            SERIES_ADDED: string;
            SERIES_UPDATED: string;
        };
        listeners: {};
        addInstance(dicomJSONDatasetOrP10ArrayBuffer: any): void;
        addInstances(instances: any, madeInClient?: boolean): void;
        updateSeriesMetadata(seriesMetadata: any): void;
        addSeriesMetadata(seriesSummaryMetadata: any, madeInClient?: boolean): void;
        addStudy(study: any): void;
        getStudyInstanceUIDs: () => any[];
        getStudy: (StudyInstanceUID: any) => any;
        getSeries: (StudyInstanceUID: any, SeriesInstanceUID: any) => any;
        getInstance: (StudyInstanceUID: any, SeriesInstanceUID: any, SOPInstanceUID: any) => any;
        getInstanceByImageId: (imageId: any) => any;
        updateMetadataForSeries: (StudyInstanceUID: any, SeriesInstanceUID: any, metadata: any) => void;
        setMetaDataProvider: (metaData: any) => void;
    } & {
        subscribe: (eventName: any, callback: any) => {
            unsubscribe: () => any;
        };
        _broadcastEvent: (eventName: any, callbackProps: any) => void;
        _unsubscribe: (eventName: any, listenerId: any) => void;
        _isValidEvent: (eventName: any) => boolean;
    };
    pubSubServiceInterface: {
        subscribe: (eventName: any, callback: any) => {
            unsubscribe: () => any;
        };
        _broadcastEvent: (eventName: any, callbackProps: any) => void;
        _unsubscribe: (eventName: any, listenerId: any) => void;
        _isValidEvent: (eventName: any) => boolean;
    };
    PubSubService: typeof PubSubService;
    PanelService: typeof PanelService;
    useActiveViewportDisplaySets: () => Types.DisplaySet[];
    WorkflowStepsService: typeof WorkflowStepsService;
    StudyPrefetcherService: typeof StudyPrefetcherService;
};
export { MODULE_TYPES, CommandsManager, ExtensionManager, HotkeysManager, ServicesManager, ServiceProvidersManager, SystemContextProvider, ViewportRefsProvider, defaults, utils, hotkeys, classes, string, user, errorHandler, object, log, DICOMWeb, CineService, CustomizationService, UIDialogService, UIModalService, UINotificationService, UIViewportDialogService, DisplaySetService, DisplaySetMessage, DisplaySetMessageList, MeasurementService, MultiMonitorService, ToolbarService, ViewportGridService, HangingProtocolService, UserAuthenticationService, IWebApiDataSource, DicomMetadataStore, pubSubServiceInterface, PubSubService, Enums, PanelService, WorkflowStepsService, StudyPrefetcherService, useSystem, useActiveViewportDisplaySets, };
export { OHIF };
export type { Types };
export type { SortDisplaySetsCopyOptions } from './utils/sortStudy';
export default OHIF;
